name: Build
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '.github/README.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '.github/README.md'
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  GRADLE_VERSION: '8.2'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Setup Build Directory
        run: |
          mkdir -p build/repos/repos
          mkdir -p build/repos/plugins
      
      - name: Build Plugin
        run: |
          ./gradlew --stop
          ./gradlew buildPlugin
      
      - name: Prepare Artifacts
        run: |
          if [ -d "build/plugins" ]; then
            find build/plugins -type f -exec cp {} build/repos/plugins/ \;
          fi
          cd build/repos
          zip -r ../repos.zip .
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repositories
          path: build/repos.zip
          retention-days: 90
          
      - name: Deploy to Builds Branch
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/repos
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch builds
          git checkout --orphan builds
          git add -A
          git commit -m "Build from commit: ${{ github.sha }}"
          git push -f "https://${{ github.actor }}:${GITHUB_TOKEN}@github.com/${{ github.repository }}" builds
