name: Build

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '.github/README.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '.github/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      - name: Setup Build Directory
        run: |
          mkdir -p build/repos/repos
          mkdir -p build/repos/plugins
      
      - name: Copy APKs to plugins directory
        run: |
          find . -name "*.apk" -exec cp {} build/repos/plugins/ \;
          cd build/repos
          zip -r ../repos.zip .
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repositories
          path: build/repos.zip
          retention-days: 90

      - name: Deploy to Builds Branch
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build/repos
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch builds
          git checkout --orphan builds
          git add -A
          git commit -m "Build from commit: ${{ github.sha }}"
          git push -f "https://${{ github.actor }}:${GITHUB_TOKEN}@github.com/${{ github.repository }}" builds
