name: Build
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug

      - name: Create repo artifacts
        run: |
          mkdir -p build/repos/repos
          mkdir -p build/repos/plugins
          ./gradlew --stop
          ./gradlew buildPlugin
          find build/plugins -type f -exec cp {} build/repos/plugins/ \;
          cd build/repos
          zip -r ../repos.zip .

      - name: Upload repositories
        uses: actions/upload-artifact@v4
        with:
          name: repositories
          path: build/repos.zip

      - name: Deploy to builds branch
        if: github.event_name == 'push'
        run: |
          cd build/repos
          git init
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan builds
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" builds
